sudo: false
language: java
jdk:
  - oraclejdk7

before_script:
  # This will download and run the Devfactory Dependency Analyser
  - git clone https://github.com/DevFactory/tpls-travis-plugin.git
  - python tpls-travis-plugin/tpls-travis-plugin.py

